### ISSUE TITLE
Reliance Jio mobile number not supported for India(IN)

### ISSUE THREAD

**Issue by jjt1bece** [googlei18n/libphonenumber#1420]
Steps to reproduce

Specify Reliance Jio mobile number in Phone Number  : 7990881369
Specify a Default Country : IN

Expected behaviour

Validation Results:
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: IN
Result from getNumberType(): MOBILE

Actual behaviour

Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: IN
Result from getNumberType(): UNKNOWN

**Comment by penmetsaa** [comment]
@jjt1bece 
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.4
https://libphonenumber.appspot.com/phonenumberparser?number=7990881369&country=IN

**Comment by JayanthB** [comment]
how about numbers starting from 70

**Comment by penmetsaa** [comment]
@JayanthB ,

Thank you for taking the time to improve libphonenumber!

We already support all phone numbers that starts with 70 and 10 digit long as mobile numbers.
https://libphonenumber.appspot.com/phonenumberparser?number=7012345678&country=IN

Please check our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md). If you want to report a new issue, please file a new one as this issue is already closed.

**Comment by aroonkv** [comment]
I am using libphonenumber-7.7.5, but the issue still exists. My number is 8848154508.
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
		PhoneNumber numberProto = phoneUtil.parse(phone, phoneUtil.getRegionCodeForCountryCode(Integer.parseInt(phoneCallingCode)));
phoneUtil.isValidNumber(numberProto)   returns false.

Please help me to resolve this issue.
